openapi: 3.0.3
info:
  description: An API to Lookup Parts by PO Number
  version: 0.0.1
  title: Coupa PO Lookup
servers:
  - url: SERVER_URL
security:
  - ApiKeyAuth: []
paths:
  /requisition_items:
    get:
      summary: List of line items on the given PO.
      description: Retrieve a page of objects from the server.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Inspections:
                    type: array
                    items:
                      $ref: "#/components/schemas/ListOfItems"
    post:
      summary: Creates a new object.
      description: Creates a new object.
      requestBody:
        description: The object to create.
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requisition_item"
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/requisition_item"
  /requisition_items/{id}:
    get:
      summary: Retrieve object.
      description: Retrieve a single object.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the desired object.
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/requisition_item"
        "404":
          description: Object was not found.
    put:
      summary: Update object.
      description: Update a single object.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the desired object.
          schema:
            type: string
      requestBody:
        description: The object to update.
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requisition_item"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/requisition_item"
        "404":
          description: Object was not found.
    delete:
      summary: Delete object.
      description: Delete a single object.
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the desired object.
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Object was not found.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-apikey
      in: header
  schemas:
    requisition_item:
      title: requisition_item
      type: object
      properties:
        id:
          description: The id of the object
          type: string
          example: hu32hu3
        created-at:
          description: The date-time of the object
          type: string
          example: 8/9/2023 9:38:51 AM
        description:
          description: The text of the object
          type: string
          example: Example description
        line-num:
          description: Line Number
          type: string
          example: Paris, France
        status:
          description: status
          type: string
        quantity:
          description: quantity
          type: number
          example: 2
        receipt-required:
          description: reveipt required yes/no
          type: string
          example: True
        updated-at:
          description: updated at date
          type: string
          example: 10/10/2023
    ListOfItems:
      title: List of objects
      type: array
      items:
        $ref: "#/components/schemas/requisition_item"
